baseURL = "https://isop-student-community.github.io/isop-student-community/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "ISoP Student Community"
theme = "ace-documentation"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
[[menu.main]]
name = "TEST"
url = ""
weight = 1
[[menu.shortcuts]]
name = "Home"
url = ""
weight = 1

[[menu.shortcuts]]
name = "Contact info"
url = "/contact/"
weight = 2


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/mutaz94/isop-student-community"
weight = 10

